function dYdt = ode1(t,Y)
%ODE1
%    DYDT = ODE1(T,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Jun-2020 15:41:58

t2 = Y(2);
t3 = Y(3);
t4 = sin(t3);
t5 = Y(4);
t6 = cos(t3);
t7 = t2.^2;
dYdt = [t2;((t2.*t4.*t5+t2.*t4.*t5.*t6).*2.0)./(t6.*2.0+t6.^2+2.0);t5;t6.*(-9.81e2./2.0e2)-t4.*t7-t4.*t6.*t7];
